### ISSUE TITLE
Error in single_prediction with xgboost model

### ISSUE THREAD

**Issue by alexakimenko** [pbiecek/DALEX#11]
There is error while running `single_prediction()` function with xgboost model:

`Error in new_observation[rep(1, nrow(data)), ] : 
  incorrect number of dimensions`

Does this function support xgb.Booster model types? 

I have DALEX_0.1.8 and breakDown_0.1.4.

**Comment by pbiecek** [comment]
Hi, I've added some small fixes in `breakDown`. 

Try also this vignette with examples for classification and regression with `xgboost`
https://pbiecek.github.io/DALEX/articles/DALEX_and_xgboost.html

**Comment by pbiecek** [comment]
@alexakimenko Let me know if you still have an issue here. It should work with latest breakDown

**Comment by alexakimenko** [comment]
Hi, it looks good now. Thank you!
