### ISSUE TITLE
the explain function in the dplyr package

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/DALEX#16]
The `explain()` method exists also in the dplyr package as the generic function.
DALEX will behave differently depending on which package is loaded first (DALEX / dplyr)
not clear how to solve this

**Comment by mstaniak** [comment]
write DALEX::explain in documentation and print a warning while loading package (similarly to how tidyverse packages print their conflicts)?

**Comment by mstaniak** [comment]
My point was that maybe people would get used to writing "DALEX::explain" after seeing it multiple times (:
