### ISSUE TITLE
`variable_response()` doesn't use `predict_function`.

### ISSUE THREAD

**Issue by agosiewska** [pbiecek/DALEX#17]
No matter which `predict_function` was passed to `explain()`, the results of the PDP plots in `variable_response` are the same.

```
 library(breakDown)
 library(randomForest)
 data(HR_data)
 HR_rf_model <- randomForest(factor(left)~., data = breakDown::HR_data, ntree = 100)
 explainer_rf  <- explain(HR_rf_model, data = HR_data,
                          predict_function = function(model, x) predict(model, x, type = "prob")[,2])
 expl_rf  <- variable_response(explainer_rf, variable = "satisfaction_level", type = "pdp")
 plot(expl_rf)
 
 
 explainer_rf_constant  <- explain(HR_rf_model, data = HR_data,
                          predict_function = function(model, x) return(0.5))
 expl_rf_constant  <- variable_response(explainer_rf_constant, variable = "satisfaction_level", type = "pdp")
 plot(expl_rf_constant)
```
Plots are the same, but should be different for different predict functions.
I think the solution is passing `predict_function` to `pdp:: partial()` by `pred.fun` parameter.

Same problem for ALE plots.

**Comment by agosiewska** [comment]
It looks like PDP is working now. But while I'm trying to calculate ALE curves, function `variable_response` shows this error: 
![image](https://user-images.githubusercontent.com/18423383/39401231-d583cda4-4b40-11e8-9040-466e2e1fc820.png)


```
library(DALEX)
library(breakDown)
library(randomForest)
data(HR_data)
HR_rf_model <- randomForest(factor(left)~., data = breakDown::HR_data, ntree = 100)
explainer_rf  <- explain(HR_rf_model, data = HR_data,
                         predict_function = function(model, x) predict(model, x, type = "prob")[,2])

expl_rf  <- variable_response(explainer_rf, variable = "satisfaction_level", type = "ale")
```

**Comment by pbiecek** [comment]
@agosiewska Thanks for checking this.
Now it should work. It turns out that pdp and ALEPlot are not that similar as expected. In the long run I will these dependencies

**Comment by agosiewska** [comment]
It works great now, thank you!
