### ISSUE TITLE
Incorrect value for `type` parameter in `variable_importance()`

### ISSUE THREAD

**Issue by agosiewska** [pbiecek/DALEX#20]
While passing a wrong parameter value, raw drop losses are calculated.
 
It would be helpful if `variable_importance()` return an error or a warning with information that `type = "raw"` was taken.

```library(DALEX)
library(randomForest)

model_regr_rf <- randomForest(m2.price~., data = apartments, ntree = 50)
explainer_regr_rf <- explain(model_regr_rf, data = apartmentsTest[1:1000, ], y = apartmentsTest$m2.price[1:1000])

variable_importance(explainer_regr_rf, type="anything")
```

**Comment by pbiecek** [comment]
The candidate solution rises an error if type is anything but "difference", "ratio", "raw"

**Comment by agosiewska** [comment]
This fixes it, thank you. I will close the issue.
