### ISSUE TITLE
"Vectorized" single_prediction

### ISSUE THREAD

**Issue by mstaniak** [pbiecek/DALEX#23]
Wouldn't it be good to let "observation" argument be a list/a df of observations to explain?

**Comment by pbiecek** [comment]
@mstaniak what shall be plotted in such case? different panels for different observations?

**Comment by mstaniak** [comment]
For starters, yes. Probably with argument specifying maximum number of instances to plot / which to plot in case user wanted to calculate many explanations, but too many plots could be a problem

**Comment by pbiecek** [comment]
This is/will be supported by the DALEX2/DrWhy.
