### ISSUE TITLE
Missspelling in article

### ISSUE THREAD

**Issue by komosinskid** [pbiecek/DALEX#28]
In article https://pbiecek.github.io/DALEX/articles/DALEX_and_xgboost.html
there is a missspelling
model_martix_train
it shoul be model_matrix_train

**Comment by pbiecek** [comment]
How the first model_martix_train is different from the second model_matrix_train?

**Comment by komosinskid** [comment]
Okay, I examined code more carefully and noticed that this little mistake is used consequently, so it doesn't affect the correctness of code execution. However, I still believe that author thought about a matrix not a martix. ;)

**Comment by pbiecek** [comment]
Ok, now I see it, 
thanks
