### ISSUE TITLE
Publications, proceedings and books about DALEX

### ISSUE THREAD

**Issue by GegznaV** [pbiecek/DALEX#32]
Are there any scientific (peer-reviewed) publications, conference proceedings or books about DALEX and related packages of the same authors that I could cite in a scientific work? Is there a place where I could find a comprehensive list of those publications?

It would be nice if this list was also included on the website of DALEX.

**Comment by mstaniak** [comment]
DALEX is a wrapper around different packages.

PDP, ICE, ALE and variable importance have citations by "outside" authors.

For factorMerger (PDP for categorical variables) there is
https://arxiv.org/abs/1709.04412
For breakDown (single_prediction/prediction_breakdown) and live there is 
https://arxiv.org/abs/1804.01955
Paper for auditor will be out soon.

Documentation with references for DALEX can be found here https://pbiecek.github.io/DALEX_docs/

**Comment by agosiewska** [comment]
Great list @mstaniak ! 
I would only add a preprint of an article about DALEX:
https://arxiv.org/abs/1806.08915

**Comment by pbiecek** [comment]
Thanks for the list above
