### ISSUE TITLE
Number of observations for PDP

### ISSUE THREAD

**Issue by mstaniak** [pbiecek/DALEX#33]
Maybe adding small barplots under PDP curve indicating how many observations for a given x value are in the dataset would be useful?

**Comment by pbiecek** [comment]
Yes, good idea. I'm refactoring the ceterisParibus package. It will take care about PDP curves, ICE curves, Interaction curves, and other things that can be calculated based on ceteris paribus curves.

**Comment by pbiecek** [comment]
Just struggling around different grammars that can be used to add rugs or residuals for observations, profiles for predictions or averages.

**Comment by pbiecek** [comment]
In the new ceterisParibus one can add rugs to the plot to present distributions for selected variables, see an example here 
https://pbiecek.github.io/ceterisParibus/articles/ceteris_paribus.html

Have you referred to something like that or something else?
