### ISSUE TITLE
Adding plot functionality to model_performance

### ISSUE THREAD

**Issue by patri01u** [pbiecek/DALEX#34]
When plotting from model_performance function, would it be possible to add functionality to limit x-axis values, as well as facets by some model factors to try to drill down into specific factors that drive the overall residuals?

Apologies in advance if these functionalities already exists. #Beginnerhere

**Comment by pbiecek** [comment]
Result from the plot function is an ggplot2 object, thus you can use `xlim()` `ylim()` or other function to zoom in some part of the plot.

But I see your point, that for `model_performance` it would be nice to have annotations for top `k` residuals. Will add to TODO

**Comment by pbiecek** [comment]
I've added a `show_outliers` parameter to `plot.model_performance()`, now you can plot names of points with largest residuals.
See an example here: https://pbiecek.github.io/DALEX/reference/plot.model_performance_explainer.html

**Comment by pbiecek** [comment]
Makes sense, will add option to select if rownames of row indexes should be presented

**Comment by 12tafran** [comment]
On a separate note, following your example on https://pbiecek.github.io/DALEX/reference/plot.model_performance_explainer.html , if you rearrange the order of arguments from  `plot(mp_rf, mp_glm, mp_lm, geom = "boxplot", show_outliers = 1)` to `plot(mp_glm, mp_lm, mp_rf,   geom = "boxplot", show_outliers = 1)`, you will get a graph where the outliers don't match the model.

It seems like we have to input the models best to worst in terms of root mean square of residuals for it to work properly

Not sure if this is an issue for you as well.
