### ISSUE TITLE
n.trees error with variable_importance() on gbm model

### ISSUE THREAD

**Issue by kransom14** [pbiecek/DALEX#35]
I get an n.trees error when trying to use the variable_importance() function on an explainer for a gbm model created with the gbm package:

```
library(gbm)
library(DALEX)

mod <- gbm(m2.price~.,data = apartments, distribution = "gaussian")

exp.mod <- explain(mod, data = apartmentsTest[,2:6],
                   y = apartmentsTest$m2.price)

vi <- variable_importance(exp.mod, loss_function = loss_root_mean_square)

Error in paste("Using", n.trees, "trees...\n") : 
  argument "n.trees" is missing, with no default

vi <- variable_importance(exp.mod, loss_function = loss_root_mean_square, n.trees = 2000)

Error in paste("Using", n.trees, "trees...\n") : 
  argument "n.trees" is missing, with no default
```

**Comment by pbiecek** [comment]
The `n.trees` function is required by the `predict()` function. The easiest way to handle this is to specify custom predict function. Se here: https://pbiecek.github.io/DALEX/reference/single_prediction.html how to do this.

Here: https://rawgit.com/pbiecek/DALEX_docs/master/vignettes/DALEX_caret.html you will find an example how to work with `gbm` and `caret`
and here https://rawgit.com/pbiecek/DALEX_docs/master/vignettes/DALEX_mlr.html
how to work with `gbm` and `mlr`.

**Comment by kransom14** [comment]
Thanks for the super documentation, this is great!
