### ISSUE TITLE
variable_response for a factor with 2 levels

### ISSUE THREAD

**Issue by ManuelSpinola** [pbiecek/DALEX#36]
I have a problem to understand a variable_response plot when the explanatory variable is a factor and has 2 levels.

library(DALEX)
library(carData)
library(randomForest)

data("Leinhardt")
df <- Leinhardt %>% select(infant, income, region, oil)
df <- na.omit(df)

rf2 <- randomForest(infant ~ income + region + oil, data = df)

rf2_exp <- DALEX::explain(rf2, data = df, y = df$infant, label = "rf")

rf2_rv  <- variable_response(rf2_exp, variable =  "oil", type = "factor")

plot(rf2_rv)

**Comment by pbiecek** [comment]
This plot is useful for larger number of levels.
For two levels you can just read how different is on average the model response
in this case 85 vs 130.

For `region` you have four levels (rf2_rv <- variable_response(rf2_exp, variable = "region", type = "factor"))
and can read that results for Africa are very different, while for Americas and Europe are most similar.

**Comment by ManuelSpinola** [comment]
Thank you very much.
