### ISSUE TITLE
bug when data was not provided in the explain()

### ISSUE THREAD

**Issue by agosiewska** [pbiecek/DALEX#5]
The description of the argument data in explain() function is:
> data - data.frame or marix - data that was used for fitting. If not provided then will be extracted from model fit

But if is not provided explainer$data is NULL.
And then function single_variable gives an error.

Example code:
```
library(DALEX)

input <- mtcars[,c("am","cyl","hp","wt")]
model.glm = glm(formula = am ~ cyl + hp + wt, data = input, family = binomial)

explainer_glm <- explain(model.glm)
expl_glm <- single_variable(explainer_glm, variable = "wt", type="pdp")
```
The code above returns the error:
Error in partial.default(explainer$model, pred.var = variable, train = explainer$data,  : 
  wt not found in the training data.

But it works with provided argument data.
```
explainer_glm <- explain(model.glm, data = input)
expl_glm <- single_variable(explainer_glm, variable = "wt", type="pdp")
```

**Comment by pbiecek** [comment]
It's not strictly a bug, since data is not obligatory for some explainers.
Though error messages should be more explicit what and why is happening.

Candidate solution: 
in functions like `single_variable()` and `single_prediction()`
the function will check if if explainer contains all required elements, otherwise will guide the user to fix it.

**Comment by agosiewska** [comment]
I probably misunderstood the earlier description of the argument.  
I thought that if the data was not provided, it would be taken from the model, for example through the function `model.frame()`

How about extracting data using `model.frame(model)` if it wasn't provided?

**Comment by pbiecek** [comment]
Yes, you are right, is should be like that.

The problem was that for some models `model.frame()` triggers an error (like gbm). 
But this can be controlled as in the latest commit.

**Comment by agosiewska** [comment]
Now it works. 
Thank you, I will close the issue.
