### ISSUE TITLE
Installation problem on Windows 10 machine

### ISSUE THREAD

**Issue by 86mm86** [pbiecek/DALEX#55]
Hi,

I tried to install both the CRAN and the GitHub version of DALEX, but I keep getting the following error

```
Error : .onLoad failed in loadNamespace() for 'sf', details:
  call: get(genname, envir = envir)
  error: object 'group_map' not found
```
The error seem to appear when installing the factorMerger library.
Any help appreciated to debug.

**Comment by pbiecek** [comment]
Thanks, will check this. 
In general I will remove dependencies from this package to make the installation lighter.

**Comment by pbiecek** [comment]
Could you try now?
```
devtools::install_github("pbiecek/DALEX")
```

factorMerger is in suggests so it should not interrupt the installation

**Comment by BogdanJastrzebski** [comment]
Same issue here: 
```
Error: .onLoad failed in loadNamespace() for 'sf', details:
  call: get(genname, envir = envir)
  error: object 'group_map' not found
```
this time on linux, while running 
```
variable_response(explainer,
+                          variable = "model_name",
+                          type = "factor")
```
probably a sa lib problem. 
Tried reinstalling Dalex and dplyr suggested in https://github.com/r-spatial/sf/issues/969.

**Comment by pbiecek** [comment]
Thanks, IMHO it's solved as factorMerger is moved to suggested
