### ISSUE TITLE
Did the prescribed: devtools::install_github("pbiecek/DALEX") but Rstudio (latest version under Linux), will not complete the DALEX install. After the above command, R will just hang and nothing happens...

### ISSUE THREAD

**Issue by sfd99** [pbiecek/DALEX#6]
Did the prescribed: 
         devtools::install_github("pbiecek/DALEX") 
but Rstudio (latest version under Linux), 
will not complete the DALEX install. 

After the above command, 
R will just hang and nothing happens...
R will just hang there.

Waited for 5 minutes,
then suspended the installation.

What am I missing
in order to install DALEX ?.
(all other R packages have installed with no problems...).

Thanks!

**Comment by ViniciusBRodrigues** [comment]
I'm having the same issue in openSUSE 42.3 and Rstudio Version 1.1.383

**Comment by pbiecek** [comment]
Could you install other packages from github?

Please let me know if this is working for you:
```
devtools::install_github("pbiecek/breakDown")
```

If not, please sent the full session_info().

**Comment by ViniciusBRodrigues** [comment]
Yes, as far as I Remember remember I can install from github, but devtools::install_github("pbiecek/breakDown") didn't work.

```
> devtools::install_github("pbiecek/breakDown")
Downloading GitHub repo pbiecek/breakDown@master
from URL https://api.github.com/repos/pbiecek/breakDown/zipball/master
Installation failed: erro ao executar comando
```

```
> devtools::session_info()
Session info ---------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.383)           
 language                             
 collate  pt_BR.UTF-8                 
 tz       America/Sao_Paulo           
 date     2018-02-26                  

Packages -------------------------------------------------------------------------
 package   * version date       source        
 base      * 3.3.1   2017-07-08 local         
 curl        2.3     2016-11-24 CRAN (R 3.3.1)
 datasets  * 3.3.1   2017-07-08 local         
 devtools    1.13.5  2018-02-18 CRAN (R 3.3.1)
 digest      0.6.10  2016-08-02 CRAN (R 3.3.1)
 git2r       0.16.0  2016-11-20 CRAN (R 3.3.1)
 graphics  * 3.3.1   2017-07-08 local         
 grDevices * 3.3.1   2017-07-08 local         
 httr        1.2.1   2016-07-03 CRAN (R 3.3.1)
 memoise     1.0.0   2016-01-29 CRAN (R 3.3.1)
 methods   * 3.3.1   2017-07-08 local         
 R6          2.2.0   2016-10-05 CRAN (R 3.3.1)
 stats     * 3.3.1   2017-07-08 local         
 tools       3.3.1   2017-07-08 local         
 utils     * 3.3.1   2017-07-08 local         
 withr       1.0.2   2016-06-20 CRAN (R 3.3.1)
 yaml        2.1.14  2016-11-12 CRAN (R 3.3.1)
```

**Comment by sfd99** [comment]
Hi Przemysław - thanks for answering!.
Yes, I could install the BreakDown pkg OK
with:
   devtools::install_github("pbiecek/breakDown") 
No problem...

But DALEX does not install.
The install command above 
(latest version R & Rstudio under Linux),
just hangs forever.

All the other 30+ R packages
have all installed OK in the past.

As requested:
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: i686-pc-linux-gnu (32-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8      
 [2] LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                 
 [9] LC_ADDRESS=C              
[10] LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8
[12] LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    yaml_2.1.16   
---
Thanks for any guidance...
SFd99
San Francisco

**Comment by pbiecek** [comment]
I have R 3.4.3 and devtools 1.13.5, and everything is working, so below you will find only my guesses

@ViniciusBRodrigues  I do not know portuguese but the error message looks like a problem with some part of devtools. Please try to download the source DALEX package from the link below and install it with install.packages() or bottom-right panel of RStudio.

@sfd99 Right now DALEX is more than 20MB (all these highres figures) so it may take some time to download (just a guess, on my computer it's 15 sec much more than for other packages). I will reduce size of large files some day, but in the meantime, please download only sources (linked below) and try to install them with install.packages() or bottom-right panel of RStudio.

If it is not enough, in one or two weeks DALEX should be at CRAN, then the installation will be easier.
Thanks

[DALEX_0.1.1.tar.gz](https://github.com/pbiecek/DALEX/files/1760923/DALEX_0.1.1.tar.gz)

**Comment by sfd99** [comment]
**Hi Przemysław,**

**Thanks!** 
Will wait for the **CRAN version of DALEX**.

_By the way,_
**Q:**
 how would you define 
the difference / similarity
between **DALEX** and  **breakDown** ?.
When to use one or the other package?.

Both seem to have great
but similar functionality... 

**SFd99
San Francisco**

**Comment by pbiecek** [comment]
breakDown is working on a level of single prediction.
DALEX is designed to be a wrapper around many different tools that may be used as a model explainers.
DALEX is using internally breakDown/pdp/ALEPlot and some other packages and unify the way in which we can work with explainers.
Like xgboost is a great library for a single type of models while caret is a wrapper around larger number of libraries with unified interface.
Hope it makes sense, It's still under heavy development

**Comment by sfd99** [comment]
Yes - thank you Przemysław .
Your clear explanation 
makes absolute sense.
(I imagine **DALEX**
also wraps the **LIME** explainer 
as well).

Will wait until you place **DALEX** in **_CRAN_**!.

**SFd99
San Francisco**

**Comment by pbiecek** [comment]
DALEX is on CRAN
https://cran.r-project.org/package=DALEX
closing this issue
