### ISSUE TITLE
v 0.1.1 is going to CRAN

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/DALEX#7]
Do we need to fix/add anything before this will be submitted?
Shapley values will get to DALEX in the next version
Support for mlr as well

**Comment by agosiewska** [comment]
If the package has not yet been sent to CRAN, it may be worth to unify the functions parameter names. 
All parameters have `_` in the name, except for `predict.function` from `explain()`.

**Comment by pbiecek** [comment]
Good point, I will change this in 0.2
(got to cran yesterday https://cran.r-project.org/package=DALEX)
