### ISSUE TITLE
DALEX with catboost support?

### ISSUE THREAD

**Issue by mwijaya3** [pbiecek/DALEX#70]
Hello, thanks for the awesome package. Is there any plan to support catboost model whether in R or Python?

Thanks!

**Comment by pbiecek** [comment]
Good idea, will add to our roadmap

**Comment by mwijaya3** [comment]
Awesome!

**Comment by maksymiuks** [comment]
Hello :)

In the following vignette you can see usage of catboost with DALEX:

https://github.com/pbiecek/DALEX_docs/blob/master/vignettes/Multilanguages_comparision.html

**Comment by mwijaya3** [comment]
Thanks @maksymiuks :).
