### ISSUE TITLE
Axis limits

### ISSUE THREAD

**Issue by bangecon** [pbiecek/DALEX#89]
Good afternoon, 
Is it possible to manipulate the axis limits on a plot in DALEX? 
For example, I might want to ignore extreme outliers for the purposes of analyzing partial dependence and focus on the range of the distribution where almost all of my other observations lie. 
Jim

**Comment by pbiecek** [comment]
DALEX is based on ggplot2, so you can use +xlim() + ylim() to add/override limits for axes
