### ISSUE TITLE
add ggplot rug to partial effects plot

### ISSUE THREAD

**Issue by spedygiorgio** [pbiecek/DALEX#91]
It could be nice to add rug to partial effects plot in order to give an idea of the distribution of the independent predictors (when numeric/continue of course)

**Comment by pbiecek** [comment]
Thanks,
it is possible with ingredients::show_rugs 
https://modeloriented.github.io/ingredients/reference/show_rugs.html

but we will try to make it simpler and more convenient

**Comment by spedygiorgio** [comment]
thanks
